controllers:
  - name:       "pid"
    topic:      "/cmd_wrench_pid"
    timeout:     0.1
    priority:    10

  - name:       "lqr"
    topic:      "/cmd_wrench_lqr"
    timeout:     0.1
    priority:    5

  - name:       "mpc"
    topic:      "/cmd_wrench_mpc"
    timeout:     0.1
    priority:    3



