#!/usr/bin/env python

import sys

from redrov_control.rqt_module import MyPlugin
from rqt_gui.main import Main

plugin = 'redrov_control'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
